Prod
Lakshman1x/API pull request #1
Opened 2024-04-22 09:24 UTC by Lakshman1x

2024-04-22 13:54 UTC, Ahsan-CloudAlly requested changes

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/controller/PersonControllerImpl.java
> +@RequestMapping("/v1/api/person")
It is more intuitive to make it /v1/api/persons because we are dealing with a collection of persons.
for example - /person/list makes me think that a list belongs to a person and we are trying to retrieve that list.
/persons or /persons/{personId} makes more sense from API resource point of view.

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/controller/PersonControllerImpl.java
> +    public ResponseEntity<Response> addPerson(@RequestBody @Valid PersonInfoDto userInput, BindingResult result) throws ValidationException, MongoAPIException {
Just return ResponseEntity of String instead of added complexity of Response object here which again includes response code.

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/controller/PersonControllerImpl.java
> +        personService.addPerson(userInput);
Also log.info that person created successfully.

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/controller/PersonControllerImpl.java
> +    public ResponseEntity<List<PersonEntity>> getList() {
Have default parameters for pagination. 
In case number of person entities grow in the database tremendously, this will slow down query performance.
Have default pagination size of 20.

Implement pagination changes through service and already existing JPA pagination.

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/exception_handler/GlobalExceptionHandler.java
> +        logger.error("Person Entity validation failed");
Is it good to hardcode that validation failed for Person entity ? 
Any other way where we can get this information ?

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/exception_handler/GlobalExceptionHandler.java
> +        Response response = new Response(HttpStatus.INTERNAL_SERVER_ERROR, "MongoDB error occurred");
Never expose application level details to end user.
Why should end user know that you are using MongoDB in backend ??

"Some error occurred. Please contact support".

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/service/PersonServicesImpl.java
> +        throw new MongoAPIException(HttpStatus.BAD_REQUEST, "Not updated, Person not found in the database, ");
I see inconsistency in response codes.

In GET and DELETE, if person does not exist response code is 404.
In case of PUT, if person does not exist, then response code is 400.

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/test/java/com/example/mongodb_api_project/controller/PersonControllerImplTest.java
> +    private PersonServicesImpl personService;
private IPersonService personService;

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/controller/PersonControllerImpl.java
> +        return new ResponseEntity<>(personRepository.findAll(), HttpStatus.OK);
Why is controller making database call directly instead of calling Service?
This is against design and outside the responsibility of Controller class.

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/controller/IPersonController.java
> +    ResponseEntity<List<PersonEntity>> getList();
This has been told before.
Entity should never be returned from the Controller.
Each entity should be mapped to corresponding dto before returning in response.

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/controller/PersonControllerImpl.java
> +        Optional<PersonEntity> person = personService.getPerson(email);
Controller shouldn't know what PersonEntity is.
That is job of Service to convert Entity to Dto.
If entity does not exist, then return Optional.empty() from Service.

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/test/java/com/example/mongodb_api_project/controller/PersonControllerImplTest.java
> +    private final String sampleLastName = "samplelastname";
Move these to TestConstants.java in src/test/resources

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/test/java/com/example/mongodb_api_project/controller/PersonControllerImplTest.java
> +    private PersonControllerImpl personController;
Does it work with IPersonController ?

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/test/java/com/example/mongodb_api_project/service/PersonServicesImplTest.java
> +import static org.mockito.Mockito.*;
wild card imports not to be used

2024-04-22 13:54 UTC, Ahsan-CloudAlly commented on src/test/java/com/example/mongodb_api_project/controller/PersonControllerImplTest.java
> +import static org.mockito.Mockito.*;
Wild card imports not to be used anywhere.

2024-04-23 04:31 UTC, Lakshman1x commented on src/test/java/com/example/mongodb_api_project/controller/PersonControllerImplTest.java
> +    private PersonControllerImpl personController;
no it doesnt

2024-04-23 06:53 UTC, Lakshman1x commented on src/main/java/com/example/mongodb_api_project/service/PersonServicesImpl.java
> +        throw new MongoAPIException(HttpStatus.BAD_REQUEST, "Not updated, Person not found in the database, ");
Changed to not found

2024-04-23 11:41 UTC, closed without merging

2024-04-23 11:59 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/service/PersonServicesImpl.java
> +                new PersonInfoDto(personEntity.getEmail(), personEntity.getFirstName(), personEntity.getFirstName()));
return list.map(this::convertToPersonInfoDto);

2024-04-23 11:59 UTC, Ahsan-CloudAlly commented on src/main/java/com/example/mongodb_api_project/controller/IPersonController.java
> +    ResponseEntity deletePerson(String mail) throws ValidationException, MongoAPIException;
Change return type to ResponseEntity<Void>.